//array of questions for little and big talk game
export const littleAndBigQuestions = [
     "Tell me something good about yourself.",
     "What was your favorite thing that happened today?",
     "What made you feel happy today?",
     "Tell me something you love about your body!",
     "Tell me something you learned today.",
     "What was something fun you did today?",
     "What is your favorite color right now?",
     "What is something you are really good at?",
     "What is your favorite food?",
     "What do you love to learn about?",
     "What do you want to do when you grow up?",
     "If you could have any superpower what would it be?",
     "What is your favorite animal? Why?",
     "What makes you feel brave?",
     "What makes you feel happy?",
     "What makes you feel strong?",
     "What was the funniest thing that happened today?",
     "What was the hardest thing about today?",
     "Who made you smile today?",
     "If you had a magic wand, what would you do first?",
     "If one wish could come true, what would you wish for?",
     "What would you name a pet dragon?",
     "Would you rather be a fish, or a bird? Why?",
     "Would you rather be a cat, or a dog? Why?",
     "Would you rather be a dolphin, or a penguin? Why?",
     "Would you rather be a tiger, or a panda? Why?",
     "What makes you feel safe?",
     "What is something you are proud of?",
]